### ISSUE TITLE
Interactive Shapes

### ISSUE THREAD

**Issue by tarrencev** [reactjs/react-art#33]
Is there a plan to add interactivity to shapes, more specifically, allowing users to move and transform shapes similar to what fabric.js does? If so, how would this be ideally implemented?

I'd be interested in contributing the functionality. Right now I am playing around with adding it through an InteractionMixin mixed in with RenderableMixin and enabling with a interactive property.

**Comment by ap050492** [comment]
Hi @tarrencev 
I want to add click event of particular shape of group in react native. I trying with difference option but i can not find any useful for that. can you please help for this issue.

```
sectionAngles.map(section => (
                <Group>                
                  <Shape
                    key={section.index}
                    d={path(section)}
                    fill={section.data.color}
                    strokeWidth={1} />
              {/* <TouchableOpacity onPress = {() => console.warn("Hi...")}> */}
                  <ART.Text font={{ fontFamily: 'Helvetica Neue', fontSize: 20, }}
                    fill="#000"
                    x={path.centroid(section)[0]}
                    y={path.centroid(section)[1]}
                    ellipsizeMode={"middle"}
                    alignment="center"
                  >{section.data.itemName}</ART.Text>
                  {/* </TouchableOpacity> */}
                 </Group>

              )) 
```
