### ISSUE TITLE
Server side rendering not working

### ISSUE THREAD

**Issue by equalbackslash** [reactjs/react-art#44]
I cant get react-art to render on the server because it relies on:

`require('art/modes/fast'); // Flip this to DOM mode for debugging`

line 14 ReactART.js

is it possible to load library in a server mode? or some mode option?

**Comment by spicyj** [comment]
No, react-art doesn't support server-side rendering.

**Comment by equalbackslash** [comment]
k, i'll just add it to my fork. i can do a pull request if you think it something other people would want

**Comment by eranimo** [comment]
At least not crashing on the server would be nice
