### ISSUE TITLE
Question on `moveChild` in ContainerMixin

### ISSUE THREAD

**Issue by fsbdev** [reactjs/react-art#50]
The `toIndex` parameter is not used and you instead have special internal logic on where to position it that ignores the `toIndex`, why is that?

I see it is a duplicate of the `createChild` method.

**Comment by spicyj** [comment]
It relies on the fact that ReactMultiChild always calls moveChild for each child, in the order they appear (regardless of whether they're updated or moved):

https://github.com/facebook/react/blob/3dc43840efd127bf2f5089b1aa7043e6d1b497de/src/renderers/shared/reconciler/ReactMultiChild.js#L296
