### ISSUE TITLE
Importing Circle doesn't work

### ISSUE THREAD

**Issue by 0x80** [reactjs/react-art#53]
Whenever I add Circle to my Electron project like  `import Circle from 'react-art/shapes/Circle'`, I get the following error: `"Uncaught TypeError: Cannot read property 'hex' of undefined", source: webpack:///./~/react-art/~/art/core/color.js? (223)`

I wonder if this is specific to Electron. I haven't tried it in a regular browser yet.

**Comment by mickhansen** [comment]
Have you tried `react-art/shapes/circle`? Works for me.
