### ISSUE TITLE
Does not work with react@0.14.0-beta3

### ISSUE THREAD

**Issue by varghesep** [reactjs/react-art#56]
In a project I can't run react@0.14.0-beta3 and react@0.13.0 together. So, I had to uninstall react@0.13.0 and make changes in the config.sys for react-art to use react@0.14.0-beta3. When I run the app, I get the following error:

Error loading http://localhost:5000/jspm_packages/npm/react@0.14.0-beta3/lib/emptyObject.js

**Comment by spicyj** [comment]
I believe this works fine except the peerDependencies version needs to be updated.
