### ISSUE TITLE
Surface render problem.

### ISSUE THREAD

**Issue by ascariandrea** [reactjs/react-art#69]
Hi,
I'm facing a problem rendering the `Surface` component.

Here is my component: 

```js
export default class RangeBar extends React.Component {
  render() {
    return (
      <div style={{ width: '300px', height: '100px' }}>
        <Surface
          width={300}
          height={100}
          style={{ cursor: 'pointer' }}>
            <Group x={0} y={0}>
              <Shape fill="#7BC7BA" d="M0 0 h 100 v 5 h -100 Z" />
            </Group>
        </Surface>
      </div>
    );
  }
}
```

What happens is that I get this error:
```js
Uncaught TypeError: element.getContext is not a function
Class.initialize	@	surface.js:25
proto.constructor	@	class.js:10
React.createClass.componentDidMount	@	ReactART.js:190
```

Looking at https://github.com/reactjs/react-art/blob/master/src/ReactART.js#L190 the `this.domNode` passed to `Mode.Surface()` isn't a dom node, but a react element.

Is this a bug or am I missing something?

Thanks :)

**Comment by spicyj** [comment]
Make sure you're on React (and ReactDOM) 0.14 too. If you're still on 0.13, React ART 0.13.1 should work.
