### ISSUE TITLE
Gradient stroke

### ISSUE THREAD

**Issue by hojberg** [reactjs/react-art#73]
Is it possible to apply a LinearGradient to a stroke on a Shape?

**Comment by hojberg** [comment]
Closing. Suppose this is better asked over on https://github.com/sebmarkbage/art

**Comment by hojberg** [comment]
Ugh, which I just realized doesn't have Issues enabled..

**Comment by sebmarkbage** [comment]
See: https://github.com/reactjs/react-art/issues/62
