### ISSUE TITLE
Cannot read property 'getPooled' of null

### ISSUE THREAD

**Issue by brentkirkland** [reactjs/react-art#76]
Hi all,

I'm using webpack to create a react app along with react-art. 

I keep getting the error `Cannot read property 'getPooled' of null` when I'm creating a simple surface such as

 `<Surface height={100} width={100}> <Shape d={'M36.7,8.1c-3.2,0-3.2-5,0-5C39.9,3.1,39.9,8.1,36.7,8.1L36.7,8.1z'} fill={'#123123'} /> </Surface>`

Has anybody ran into this issue with webpack, or is this a possible problem with react-art? Thanks!

(I'm mostly only familiar with React ART within iOS, so maybe it's different for webpack? no idea)

**Comment by brentkirkland** [comment]
I wasn't bundling it correctly in webpack

**Comment by jiereal** [comment]
You should write the solution,instead of simply close it.

**Comment by Kaitsh** [comment]
@brentkirkland what was your solution? I have the same problem.
