### ISSUE TITLE
Could not find `react/lib/Object.assign` on react v15.0.1

### ISSUE THREAD

**Issue by RaoHai** [reactjs/react-art#89]
```
FAIL  __tests__/ReactART-test.js
● Runtime Error
Error: Cannot find module 'react/lib/Object.assign' from '/Users/raohai/works/react-art/src/ReactART.js'
```

https://github.com/reactjs/react-art/blob/master/src/ReactART.js#L27

**Comment by zpao** [comment]
We will need to update ReactART for v15 to fix this and maybe one other issue. We'll ship that soon.

**Comment by zpao** [comment]
Closing out because no published version claims compatibility with React 15. The next published version will work.

**Comment by adamtal3** [comment]
When will you publish the next version? I'm still having this error if I install the latest version from npm

**Comment by shanky-munjal** [comment]
I am also facing this issue. I am using react -15.2.1

**Comment by spicyj** [comment]
react-art 0.15.1 should work fine.
