### ISSUE TITLE
Warning: ReactDebugTool: debugID may not be empty.

### ISSUE THREAD

**Issue by sherdeadlock** [reactjs/react-art#97]
I get this warning when I upgrade my project to react 15.1

<img width="930" alt="screen shot 2016-06-26 at 11 56 03 pm" src="https://cloud.githubusercontent.com/assets/6625010/16363354/2ae7eaee-3bfa-11e6-8e09-8181b490f827.png">

**Comment by sherdeadlock** [comment]
Sorry, it doesn't happened in release build.

**Comment by jjeising** [comment]
Could you please reopen this? This isn't a problem when building for production but definitely an incompatibility with the current React version.

**Comment by zpao** [comment]
Is this still a problem in 15.2.0?

**Comment by jjeising** [comment]
@zpao Looks like it works fine with react 15.2.0. We now have warnings for `tabindex` and `accesskey` properties for canvas, but that's a separate issue and easy to fix. Thanks for the hint.

**Comment by zpao** [comment]
Thanks for confirming!
